# Generated by Django 5.2.5 on 2025-09-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_auditlog_action_alter_currency_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringbill',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
