# Generated by Django 5.2.5 on 2025-09-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_recurringbill_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='spent_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
