# Generated by Django 5.2.5 on 2025-09-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_notification_options_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_verification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
