# Generated by Django 5.2.5 on 2025-09-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_last_verification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_window_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
